### ISSUE TITLE
Decidim API not working with Plans module on v0.22

### ISSUE THREAD

**Issue by PierreMesure** [mainio/decidim-module-plans#44]
Hi Antti,

I was testing this module and noticed that it breaks the API, also breaking the comments in the process.

Here's the stacktrace:
```
NameError (uninitialized constant Decidim::Plans::Api::TimestampsInterface):
  
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `rescue in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:56:in `load_missing_constant'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/lib/decidim/plans/api/content_interface.rb:8:in `<module:ContentInterface>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/lib/decidim/plans/api/content_interface.rb:6:in `<module:Api>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/lib/decidim/plans/api/content_interface.rb:5:in `<module:Plans>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/lib/decidim/plans/api/content_interface.rb:4:in `<module:Decidim>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/lib/decidim/plans/api/content_interface.rb:3:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/section_content/content_type.rb:10:in `<class:ContentType>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/section_content/content_type.rb:6:in `<module:SectionContent>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/section_content/content_type.rb:5:in `<module:Plans>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/section_content/content_type.rb:4:in `<module:Decidim>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/section_content/content_type.rb:3:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.4.4) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:13:in `loading'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/content_subject.rb:12:in `<class:ContentSubject>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/content_subject.rb:7:in `<module:Plans>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/content_subject.rb:4:in `<module:Decidim>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/content_subject.rb:3:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.4.4) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:13:in `loading'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plan_type.rb:41:in `<class:PlanType>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plan_type.rb:5:in `<module:Plans>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plan_type.rb:4:in `<module:Decidim>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plan_type.rb:3:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.4.4) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:13:in `loading'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plans_type.rb:11:in `<class:PlansType>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plans_type.rb:5:in `<module:Plans>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plans_type.rb:4:in `<module:Decidim>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-module-plans-61d88f345d32/app/types/decidim/plans/plans_type.rb:3:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.4.4) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:13:in `loading'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
activesupport (5.2.4.4) lib/active_support/inflector/methods.rb:285:in `const_get'
activesupport (5.2.4.4) lib/active_support/inflector/methods.rb:285:in `block in constantize'
activesupport (5.2.4.4) lib/active_support/inflector/methods.rb:281:in `each'
activesupport (5.2.4.4) lib/active_support/inflector/methods.rb:281:in `inject'
activesupport (5.2.4.4) lib/active_support/inflector/methods.rb:281:in `constantize'
activesupport (5.2.4.4) lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/lib/decidim/api.rb:14:in `map'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/lib/decidim/api.rb:14:in `orphan_types'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/app/types/decidim/api/schema.rb:14:in `block in <module:Api>'
graphql (1.9.21) lib/graphql/define/instance_definable.rb:166:in `instance_eval'
graphql (1.9.21) lib/graphql/define/instance_definable.rb:166:in `ensure_defined'
graphql (1.9.21) lib/graphql/schema.rb:292:in `define'
graphql (1.9.21) lib/graphql/define/instance_definable.rb:233:in `define'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/app/types/decidim/api/schema.rb:6:in `<module:Api>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/app/types/decidim/api/schema.rb:4:in `<module:Decidim>'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/app/types/decidim/api/schema.rb:3:in `<main>'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:14:in `block in loading'
activesupport (5.2.4.4) lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
activesupport (5.2.4.4) lib/active_support/dependencies/interlock.rb:13:in `loading'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
bootsnap (1.3.2) lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-api/app/controllers/decidim/api/queries_controller.rb:11:in `create'
actionpack (5.2.4.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.4) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
activesupport (5.2.4.4) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-core/app/controllers/concerns/decidim/use_organization_time_zone.rb:21:in `use_organization_time_zone'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sentry-raven (2.11.1) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.4) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.4) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.4) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.4) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.4) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.4) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.4) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.4) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
railties (5.2.4.4) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.4.4) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.4.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
railties (5.2.4.4) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.4.4) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.4.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.4) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.4) lib/action_dispatch/routing/route_set.rb:840:in `call'
batch-loader (1.5.0) lib/batch_loader/middleware.rb:11:in `call'
omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-core/app/middleware/decidim/strip_x_forwarded_host.rb:11:in `call'
/Users/Pierre/.rvm/gems/ruby-2.6.3/bundler/gems/decidim-e0cb3a1ee409/decidim-core/app/middleware/decidim/current_organization.rb:21:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.4) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
activesupport (5.2.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
sentry-raven (2.11.1) lib/raven/integrations/rack.rb:51:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

I filed an issue on the decidim repo ([#6841](https://github.com/decidim/decidim/issues/6841)). It seems to be appearing on [try.decidim.org](try.decidim.org) which doesn't use this module so I'm not sure what the root cause is. Removing your module solved the problem for me...

**Comment by ahukkanen** [comment]
Yes, master is broken right now.

Thanks for pointing out this issue.

**Comment by ahukkanen** [comment]
Should work now, see the release branches.
